<a href="https://colab.research.google.com/github/Rohanrathod7/my-ds-labs/blob/main/16_Working_with_Categorical_Data_in_Python/01_Introduction_to_Categorical_Data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import pandas as pd

In [15]:
url = "https://raw.githubusercontent.com/Rohanrathod7/my-ds-labs/main/14_Exploratory_Data_Analysis_in_Python/dataset/salaries.csv"
salaries = pd.read_csv(url)
display(salaries.head())
salaries["date_of_response"] = pd.to_datetime(salaries["date_of_response"])

,Designation,date_of_response,Experience,Employment_Status,Salary_In_Rupees,Employee_Location,Company_Location,Company_Size,Remote_Working_Ratio,Salary_USD,Job_Category,month,weekday
0,Machine Learning Scientist,2020-01-07,SE,FT,20688070.0,JP,JP,S,0.0,248256.840,Machine Learning,1,1
1,Big Data Engineer,2020-09-19,SE,FT,8674985.0,GB,GB,M,50.0,104099.820,Data Engineering,9,5
2,Product Data Analyst,2020-11-21,MI,FT,1591390.0,HN,HN,S,0.0,19096.680,Data Analytics,11,5
3,Machine Learning Engineer,2020-11-29,SE,FT,11935425.0,US,US,L,50.0,143225.100,Machine Learning,11,6
4,Data Analyst,2020-09-07,EN,FT,5729004.0,US,US,L,100.0,68748.048,Data Analytics,9,0